Word_count.exe: main.o add_word.o dump_wrod.o finalize.o get_word.o initilize.o
	gcc -o Word_count main.o add_word.o dump_wrod.o finalize.o get_word.o initilize.o
main.o: main.c
	gcc -c main.c
add_word.o: add_word.c
	gcc -c add_word.c
dump_wrod.o: dump_wrod.c
	gcc -c dump_wrod.c
finalize.o: finalize.c
	gcc -c finalize.c
get_word.o: get_word.c
	gcc -c get_word.c
initilize.o: initilize.c
	gcc -c initilize.c